name: GitHub Actions Homework
run-name: Hello World Workflow
on: [push]
jobs:
  Run-Hello-World:
    name: Built and run on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++-10]
        include:
          - os: ubuntu-latest
            compiler: g++-10

          - os: macos-latest
            compiler: g++-10

          - os: windows-latest
            compiler: cl

    steps:
      - uses: actions/checkout@v3
      - name: windows build
        if: startsWith(matrix.os, 'windows')
        run: sh compile.sh exe
      # - name: setup for windows
      #   if: startsWith(matrix.os, 'windows')
      #   run: |
      #     cd ..
      #     git clone https://github.com/Microsoft/vcpkg.git
      #     cd vcpkg
      #     git checkout --force 2020.01
      #     .\bootstrap-vcpkg.bat
      #     .\vcpkg.exe install cppzmq:x64-windows

      # - name: Running cmake (windows)
      #   if: startsWith(matrix.config.os, 'windows')
      #   run: |
      #     cd ${{ github.workspace }}
      #     mkdir build
      #     cd build
      #     cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}
      #               /../vcpkg/scripts/buildsystems/vcpkg.cmake

      # - name: Build Solution (windows)
      #   if: startsWith(matrix.config.os, 'windows')
      #   run: |
      #     cd build
      #     MSBuild.exe CMakeHelloWorld.sln

      - run: make hello
      - run: ./hello
