name: GitHub Actions Homework
run-name: Hello World Workflow
on: [push]
jobs:
  Run-Hello-World:
    name: Built and run on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++-10]
        include:
          - os: ubuntu-latest
            compiler: g++-10

          - os: macos-latest
            compiler: g++-10

          - os: windows-latest
            compiler: gcc

    steps:
      - uses: actions/checkout@v3

      - name: windows build
        if: startsWith(matrix.os, 'windows')
        run: gcc -Wall hello.c -o hello

      - name: windows run
        if: startsWith(matrix.os, 'windows')
        run: ./hello

      - name: other run
        if: startsWith(matrix.os, 'ubuntu') | startsWith(matrix.os, 'macos')
        run: make hello
        run: ./hello
