name: GitHub Actions Homework
run-name: Hello World Workflow
on: [push]
jobs:
  Run-Hello-World:
    name: Built and run on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++-10]
        include:
          - os: ubuntu-latest
            compiler: g++-10

          - os: macos-latest
            compiler: g++-10

          - os: windows-latest
            compiler: cl

    steps:
      - uses: actions/checkout@v3
      - run: make hello
      - run: ./hello
